# Generated by Django 4.0.5 on 2022-07-05 15:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(default='posts/default.jpg', upload_to='upload_to', verbose_name='image')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='Draft', max_length=10)),
            ],
        ),
    ]
