# Generated by Django 4.0.5 on 2022-07-07 06:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0002_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='what Good'),
            preserve_default=False,
        ),
    ]
