# Generated by Django 4.0.5 on 2022-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='create_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
